### ISSUE TITLE
Refactor to use crypto-ld 4.0 API

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/x25519-key-agreement-key-2019#10]
To match https://github.com/digitalbazaar/ed25519-verification-key-2018/pull/1 and https://github.com/digitalbazaar/crypto-ld/pull/47.

Also rename repo to `x25519-key-agreement-key-2019` and re-publish on NPM as `@digitalbazaar/x25519-key-agreement-key-2019`.

**Comment by dlongley** [comment]
This happened, closing.
